### ISSUE TITLE
Playlist editor: up/down arrows on special tracks

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#101]
Hello Eric,

You had mentioned that the up/down arrows were not working on nmes.  Is this still the case for you?

I am not able to reproduce; for me, up/down work on entries of all types.  Can you please confirm in stage?

Also, I find up/down a little tedious and archaic.  As an enhancement, could we do a visual 'handle' that one could grab and use to drag tracks around? Or something like that.  I can assist with the database/backend part of it if you can do the UI, because it will require something of a rethink on the backend to support.

**Comment by eric-gilbertson** [comment]
hey jim,

i can no longer reproduce this issue on staging.  

regarding the addition of DnD playlist editing, i wonder if this won't make the list too editable. seems that one advantage of the current implementation is that it discourages adhoc editing of the list while still allowing rejiggering of a forgotten item and that we wanted to discourage general editing of event time. it does seem too that the usability of the current scheme could be greatly enhanced by doing the swap with a DOM manipulation rather than a post.

**Comment by RocketMan** [comment]
Closing as non reproducible.

I support moving track up/down and edit to Ajax; I think this will go a long way to helping with the usability.
