### ISSUE TITLE
Disk title capitalization is changed when submitting a new disk

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#111]
Disk title capitalization is changed when submitting a new disk. See "III" by the Lumineers which was entered as three uppercase 'i' characters. Upon submission the title became 'Iii' presumably because somewhere in the input validation process the second two 'I' characters are automatically converted it 'i'.

Suggested Fix:
update title in the DB to 'III' and disable any name processing so that the name is recorded as it was entered by the reviewer.

**Comment by RocketMan** [comment]
This is a tricky one.  I have devised a compromise:

1. Effective with this change, in the Library Editor, if an artist, track, or title is entered with capitalization already in place, then it will not be touched at all.  Thus, Roman numerals like III and names like O'Brien and TenKate will appear exactly as they are entered.

2. If a Library Editor entry is entered in lower case, then it will be capitalized as usual, with one enhancement: Certain words will no longer be capitalized unless they are first or last; e.g., 'of', 'for', 'by', 'about', 'the', 'a'.  This follows the usual convention of title capitalization in English.  Thus, keying in all lower case, 'the taming of the shrew' will now yield, 'Taming of the Shrew, The'.  (Previously, this would have been 'Taming Of The Shrew, The')

One possible shortcoming to the new approach:  If a keyer has the caps-lock key on (I am thinking Byrd here; there may be other keyers like this as well), then the whole title WILL NOW SCREAM AT YOU LIKE THIS.  Previously, this would have been fixed by the automatic capitalization routine.  Will monitor and adjust as needed.
