### ISSUE TITLE
Recent reviews page does not show the most recent reviews

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#154]
Recent reviews page does not show the most recent reviews. It shows both older reviews, eg Bachanala (review date 2015-12-16) and it does not show some of the most recent reviews, eg Headlight by Della Mae (review date 2020-03-29). 

Reproduce:
   * log into zookeeper.standford.edu
   * click Recent Reviews

**Comment by RocketMan** [comment]
A 'recent review' is one that is two weeks old or less, or is in the a-file.
Headlight is not shown because it was not reviewed in the past two weeks.
Bachanala is shown because it is still in the a-file.

Not sure how this can be fixed given that the music department is on hold (no adds, little to no new music).

**Comment by eric-gilbertson** [comment]
I suggest that the display rule be modified to show the most recent reviews regardless of their A file status.  This would provide a known place for DJs to find all new reviews independent of the A file activity (or lack thereof). I would also note that the there is a separate page for viewing A file content and that separating this behavior clarifies the purpose of both pages.

 If it makes any difference, I can make this change since I already have a pending change to add the reviewed date to the display.

**Comment by RocketMan** [comment]
> I suggest that the display rule be modified to show the most recent reviews regardless of their A file status. This would provide a known place for DJs to find all new reviews independent of the A file activity (or lack thereof). I would also note that the there is a separate page for viewing A file content and that separating this behavior clarifies the purpose of both pages.

A-file is included because you requested it in #46.

Recent Reviews is already showing recent reviews that are not in the A-File.  'Recent' in this case is defined as 2 weeks.  We could extend it from 2 weeks to 4, 6, or even 8 weeks, but it still would not catch Headlight.  There just are not that many recent reviews right now.  Interesting times and all.

> If it makes any difference, I can make this change since I already have a pending change to add the reviewed date to the display.

Excellent. thanks!  The reviewed date will be very helpful.  Please do a PR with whatever changes you propose and we can go from there.

**Comment by RocketMan** [comment]
FYI, I just merged hotfix-2-9-0 to master.  master is now up-to-date with the latest code from prod.

**Comment by eric-gilbertson** [comment]
yes, i guess i did suggest including all A file items in the recently reviewed list, didn't i. i think that at the time i was not aware of the separate A file list page. regardless of the history, i would now suggest the following for the recent reviews page:

    *  add  "Date" column to table (far right column) and make it sortable
    * display all reviews in the last X weeks
    * add paging support that allows viewing older reviews

It may also be worth adding the ability to search by DJ (with a default of "All") but at this point it might be best to leave this feature as a future item.

**Comment by eric-gilbertson** [comment]
It would be helpful for those of us still doing shows to have this change deployed soon so that recently submitted reviews are visible. If you do not plan on deploying v2.10.0 branch soon would you merge this change the currently deployed branch?

**Comment by RocketMan** [comment]
It's in stage, so you can access it there.

For future contributions, if you want to land a patch against the current release, base it against the hotfix-* branch, and base new features to master.  It's easy to merge hotfix to master to pick up features for forward development, but cherry picking from master to hotfix is a can of worms.

**Comment by RocketMan** [comment]
Patch landed hotfix, master; closing.
