### ISSUE TITLE
Recent reviews page does not display all recent reviews

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#168]
Recent reviews page does not display all recent reviews. BeSharp's review of Headlights by Della Mae (review date 3/29/2020) is an example of a review that is missing.

**Comment by RocketMan** [comment]
This is because we are limiting the number of reviews on that page to 50.  It turns out there are just 50 reviews more recent than that one.

Not sure what you want to do about that.  Bump the limit?

(Note the 'date' shown on the Recent Reviews page is the album date, not the review date.  So that's why you see Love What Survives and Fathoms on there.  These albums are from 2018, but the reviews are new (June 2020).

**Comment by eric-gilbertson** [comment]
The confusion is rooted in the display of the album and not the review date. Can this be changed?

**Comment by RocketMan** [comment]
> The confusion is rooted in the display of the album and not the review date. Can this be changed?

Yes, I will fix it.
