### ISSUE TITLE
Include track title in Recent Airplay table in Review page

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#179]
As a DJ I would like to know which tracks I've played recently in the Review page so that I don't over play tracks from an A file disk. Currently the recent plays list includes both the DJ name and the show name. In order to keep the presentation simple, suggest eliminating the DJ name and showing the show name and track name instead. Also, recommend changing the date format to numeric so that it matches the other dates in the page

**Comment by RocketMan** [comment]
Sounds good.  I've updated IPlaylist::getLastPlays to return the track name in 'lasttrack'.  You can use this to update the UI to show the track.

This is on hotfix-2-10-2.

**Comment by RocketMan** [comment]
A DJ might well spin more than one track from the album.  To that end, I've updated getLastPlays to return, in addition to 'lasttrack', a new value 'tracks', which is an array with the names of all tracks spun during that show.

I would have no objection to seeing all played tracks under the show name.  In fact, it probably makes sense to show them all rather than just one, if there is more than one.
