### ISSUE TITLE
Spin publishing should fire only from the most recent playlist when there are multiple lists active

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#299]
Spin publishing should fire only from the most recent playlist when there are multiple lists active. Currently if there are two playlists for a given date & time then the spins from both lists will be published. This a problem when a DJ does a last minute fill in show over a slot that had been scheduled for rebroadcast. Current work around is to not submit a rebroadcast playlist for slots that MAY be covered by a live show. 

SUGGESTED CHANGE:
In the case of multiple playlists for a given date/time publish the spins only from the newest list.

**Comment by RocketMan** [comment]
Good catch!  In the event of overlapping lists, live events fire from the most recent list only, BUT the look-back for Recently Played on the home page hits overlapping lists, such that the cards display for both lists.

There is a situation which we should be aware:  Sometimes a DJ will create multiple overlapping lists unintentionally, because it seems the usability of New Playlist/Edit Playlist is not intuitive.  It's discussed in #84.  Just so we are aware, the fix to this issue without also addressing #84 could result in suppression of valid tracks.  I think that's acceptable for now, but I would also like to see a solution for #84.
