### ISSUE TITLE
Feature request: album track times

### ISSUE THREAD

**Issue by bufordsharkley** [RocketMan/zookeeper#432]
This is a big ask, but I think that incorporating track times as a possible entry for each ZK album would make a good deal of sense

* We have started printing track times on the back cover of new A-file adds (currently by printing iTunes playlists), which have proved useful
* A goal we have is to auto-compose all the information for a new CD-R add, but unfortunately we don't have this information currently available in ZK
* Discogs definitely has track times in all cases, so including it as part of the Discogs import is doable, and would save time on manual input

Doing this for *old* entries would generally be way too hairy, and generally not worth it, but it would be nice to have this as standard for new adds going forward at some point.

Thoughts?

**Comment by RocketMan** [comment]
@bufordsharkley Thanks for making these suggestions.  Input from the music department as to how you are actually using the software is most appreciated.

As it turns out, we are already downloading track times from discogs as part of track pre-population but doing nothing with them at present, with the idea that someday we would.  Given you are actually using this information, it makes sense to add it.  I will be happy to take this on.
