### ISSUE TITLE
Set CORS 'Access-Control-Allow-Origin' header in REST responses

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#80]
Currently external web pages cannot request the 'onnow' list because of CORS restrictions. Setting the Access-Control-Allow-Origin to '*' for all REST responses will allow ZK to more easily interact with other applications.

**Comment by RocketMan** [comment]
We currently support CORS via the `allowed_domains` setting in config.php.  Add any domains you want to support in there.

I don't think turning off CORS is necessarily a good idea.

**Comment by eric-gilbertson** [comment]
What makes you say the CORS should not be disabled for the REST requests? The modern web runs on REST interfaces that allow general access in order to build client side mashup views. It isn't really preventing access because the same thing can be achieved by proxying through the host server but this requires more code and increased latency.

**Comment by RocketMan** [comment]
Who said anything about preventing access?  That is not the point of CORS.

You don't have to 'proxy' through anything to use REST APIs in zookeeper from kzsu.stanford.edu or any other station resource.  We already return the `Access-Control-Allow-Origin` header for all hosts in the stanford.edu domain, as well as kzsu.org and kzsu.fm.

The reason Mark M proxied onnow was not CORS, but rather because zk was returning xml and he wanted json, so he used a proxy to transform it.  You can now ask zk to return json, so that is no longer necessary.

Also, I did not say CORS should not be disabled; I said disabling it was not necessarily a good idea.  Think for example about how zookeeper sessions work (cookies) and how that is going to affect state-changing APIs that would be subject to XSS if CORS were allowed globally.  I am open to disabling it (selectively) if there is a good case to be made, and it does not run afoul of any industry standard security practices.

**Comment by RocketMan** [comment]
Closing, because we already support CORS within the organization.  If you serve up JavaScript content from kzsu.stanford.edu, it can call zookeeper APIs directly with no problem.  This is available right now.

Setting the Access-Control-Allow-Origin to '*' for all REST responses is inadvisable; see [How to Securely Implement Cross-Origin Resource Sharing (CORS)](https://www.pivotpointsecurity.com/blog/cross-origin-resource-sharing-security/).

If you want to allow random sites on the internet to be able to serve up content that scripts zookeeper, then open a ticket and we will review it on a per-API basis.

**Comment by eric-gilbertson** [comment]
The onnow REST request does not require authorization so there is no security impact in allowing it to be accessed from the browser, eg setting CORS access to it to "*".  OTOH allowing it does greatly simplify the process for external developers to utilize the data in javascript. To do this currently one must either deploy an instance of Zookeeper or request that their IP be added to the production white list (assuming that they even have a fixed IP or DNS name).

**Comment by RocketMan** [comment]
There is no IP address or domain whitelist.  The `allowed_domains` configuration setting lists the domains that are accepted for the Origin header.  It is about preventing cross scripting, not about restricting access.

That said, I have no objection to opening onnow for cross scripting.  Is this just for development, or will some production site somewhere be cross scripting this API?

**Comment by RocketMan** [comment]
Patch landed and deployed to prod.

I still want to understand the envisioned use cases around cross-origin scripting.  If we're thinking that zookeeper content will be mashed, then we will want to consider what and how the information will be used, both for our own sake and for ease of development of any external integrators.

**Comment by eric-gilbertson** [comment]
Immediate use case is to allow external developers (eg me) to include the 'on now' list into their own web pages.  Example being modifying the station web site client's to directly access this information without the need for a proxy. Currently the development of this feature can only be done from a KZSU server due to CORS. As mentioned previously, this data is freely available when obtained via a proxy server, so I do not understand your resistance to allowing browsers to fetch this data directly?

**Comment by RocketMan** [comment]
The onNow API is now fully open for cross-origin scripting.

Just because data are freely available via a proxy does not mean CORS and the same-origin policy have no value; they are solving a different problem.  I refer you to the link in the comment above for the reasons behind CORS and best practices for approaching it.

I have no problem with relaxing other APIs for cross origin scripting outside the organization, but it needs to be understood that is what we are doing, and we need to document it.

**Comment by eric-gilbertson** [comment]
Sounds good. Thanks.
