### ISSUE TITLE
Restore CRUD support for DJ name field

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#82]
Restore CRUD support for DJ name field. In the most recent version of ZK the DJ names are implicitly saved to the DB when a PL is created with a new value. One issue with this is that a new value will be persisted when a uses mistypes their DJ name and there does not appear to be any way to remove entries. Suggest restoring the previous behavior where DJ names are explicitly managed via user actions, eg add/delete operations.

**Comment by RocketMan** [comment]
There was never a DJ delete function, nor any way to manage the list of airnames.

The only thing that changed is that an explicit "add new airname" is no longer required.

Currently workflow is that the field should have a combo list with the already existing names, so if the user starts typing, one of those should match and highlight.  If that is not happening, then we can look into it.

Also, we could look at adding an airname management screen that would allow merging or deleting of airnames.

**Comment by eric-gilbertson** [comment]
A good first start on this is to restore the 'add name' link thereby making the addition of new air names an explicit operation and reducing the likelihood of accidental name additions.

**Comment by RocketMan** [comment]
Yes, making the action explicit would help.  Another way would be to display a confirmation dialog if the airname is new.  However, I don't think a confirmation dialog or the 'add name' link is getting at the root problem.

Think about show name:  It is a free form field similar to air name.  It is often the same for each show.  As with airname, DJs sometimes make mistakes keying it in.

Why is air name a problem and show name not?  It is this:  You can go back and fix errors in both show name and air name, however bad show names just disappear but bad air names do not go away, and there is no way to delete them.

Air names that have no associated shows have no value.  They should just vanish automatically.

Whether air name creation is explicit ('add name' link) or implicit (like show name), they should definitely behave more like show names.  As a first step, I am going to auto-prune the DJ's air name list each time it is brought up, so that any air names which have no linked playlists will be automatically purged.  In this way, air names will behave exactly like show names.

**Comment by RocketMan** [comment]
Patch landed prod.

Let's see how this goes.  Should be no change in workflow for the users, so I am not going to announce.  Feel free to communicate if you want.

**Comment by RocketMan** [comment]
Actually, I will go ahead and send out a communication.  I don't want anyone to be alarmed that airnames are disappearing.

**Comment by RocketMan** [comment]
Airname functionality now works more like a smart list:  Airnames are now automatically created when first referenced, and are now automatically deleted when no longer in use.

In addition, I have just committed enhancement 9c05518 to allow updates to the airname from the Update Profile page.

Closing, as airname creation, update, and deletion are now supported.
