### ISSUE TITLE
Regression: home page font

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#95]
'On Now' and 'Top 10 Albums' headers have different weights, giving the appearance of mixed fonts on the page.

Expected:  'On Now' and 'Top 10 Albums' should either both be bold, or both be normal.

**Comment by eric-gilbertson** [comment]
Actually, the two lines do use different fonts, eg helvetica vs verdana. this is because the font-family list for body is "Helvetica, Verdana, Arial, sans-serif", while for many other classes, eg " verdana, arial, helvetica, sans-serif". my recommendation is to eliminate the latter in order to avoid DRY and to provide consistent typography.  Suggest also that you handle this since I do not now the rationale for the existing setup.

**Comment by RocketMan** [comment]
Good one!

I removed all of the verdana-first font lists, except for the couple that are intended for smaller than usual text.  Let's see how that goes, and we can remove those as well as needed.

Closing, as the home page fonts now look as expected.

**Comment by eric-gilbertson** [comment]
Yes, definitely looks better now. I wonder though if the font size should be increased a bit since helvetica has a smaller 'foot print' than verdana and it now reads a little on the small size to me.
